# Employee Data

In [141]:
import numpy as np
from numpy import genfromtxt

Employee_data=genfromtxt("C:/Users/acer/Downloads/DS1_C4_S1_Employee_Data_Challenge.csv",delimiter=',',skip_header=1)
Employee_data

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

# Task 1

In [254]:
Employee_data[0:,1].mean()
print("\n Average Age of all Employees:",Employee_data[0:,1].mean())


 Average Age of all Employees: 28.26


# Task 2

In [154]:
Emp=np.where(Employee_data[0:,1]>25)
np.size(Emp)

38

In [263]:
print("\nTotal No. of employees who are over 25 years old:",np.size(Emp),"\n\n",Employee_data[Emp])


Total No. of employees who are over 25 years old: 38 

 [[ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [37. 28.]
 [38. 28.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [49. 32.]
 [50. 34.]]


# Task 3

In [262]:
Emp_30=np.where((Employee_data[0:,1]>30) & (Employee_data[0:,1]<35))
print("\nTotal No. of Employees whose age b/w 30 and 35:",np.size(Emp_30),"\n\nEmployees whose age b/w 30 and 35 ","\n",
      Employee_data[Emp_30])


Total No. of Employees whose age b/w 30 and 35: 9 

Employees whose age b/w 30 and 35  
 [[ 3. 31.]
 [10. 32.]
 [16. 33.]
 [32. 32.]
 [41. 32.]
 [43. 33.]
 [44. 31.]
 [49. 32.]
 [50. 34.]]


# Shopping Data 

In [150]:
import numpy as np
from numpy import genfromtxt

Shopping_data=genfromtxt("C:/Users/acer/Downloads/DS1_C4_S1_Shopping_Data_Challenge.csv",delimiter=',',skip_header=1)
Shopping_data

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

In [57]:
Shopping_data.size

800

# Task 1

In [253]:
Sp_80=np.where(Shopping_data[0: ,3]>80)

print("Total no. of Customers whose spending score is more than 80:",np.size(Sp_80),"Such Customers")


Total no. of Customers whose spending score is more than 80: 30 Such Customers


In [248]:

print("\n Customers whose spending score is more than 80:","\n\n",Shopping_data[Sp_80])


 Customers whose spending score is more than 80: 

 [[  2.  21.  15.  81.]
 [  8.  23.  18.  94.]
 [ 12.  35.  19.  99.]
 [ 20.  35.  23.  98.]
 [ 26.  29.  28.  82.]
 [ 30.  23.  29.  87.]
 [ 34.  18.  33.  92.]
 [ 36.  21.  33.  81.]
 [ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [156.  27.  78.  89.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [200.  30. 137.  83.]]


# Task 2

In [240]:
Sp_age=np.where((Shopping_data[0: ,1]>=20) & (Shopping_data[0: ,1]<=24))
Sp_age

(array([  1,   2,   3,   5,   7,  13,  15,  17,  29,  31,  35,  39,  41,
         45,  78,  84,  87,  95,  99, 100, 105, 124, 134], dtype=int64),)

In [245]:
Shopping_data[Sp_age]


array([[  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  6.,  22.,  17.,  76.],
       [  8.,  23.,  18.,  94.],
       [ 14.,  24.,  20.,  77.],
       [ 16.,  22.,  20.,  79.],
       [ 18.,  20.,  21.,  66.],
       [ 30.,  23.,  29.,  87.],
       [ 32.,  21.,  30.,  73.],
       [ 36.,  21.,  33.,  81.],
       [ 40.,  20.,  37.,  75.],
       [ 42.,  24.,  38.,  92.],
       [ 46.,  24.,  39.,  65.],
       [ 79.,  23.,  54.,  52.],
       [ 85.,  21.,  54.,  57.],
       [ 88.,  22.,  57.,  55.],
       [ 96.,  24.,  60.,  52.],
       [100.,  20.,  61.,  49.],
       [101.,  23.,  62.,  41.],
       [106.,  21.,  62.,  42.],
       [125.,  23.,  70.,  29.],
       [135.,  20.,  73.,   5.]])

In [237]:
Age=np.sort(Shopping_data[Sp_age][0:,1])
Age

array([20., 20., 20., 20., 20., 21., 21., 21., 21., 21., 22., 22., 22.,
       23., 23., 23., 23., 23., 23., 24., 24., 24., 24.])

# Task 3

In [192]:
Cust_idmin=Shopping_data[0: ,2].min()
Cust_idmin

Custmin=np.where(Shopping_data[0: ,2]==Cust_idmin)
print("\nLowest annual income:",Cust_idmin,"\n","\nIds of employees having Lowest annual income:","\n",Shopping_data[Custmin])


Lowest annual income: 15.0 
 
Ids of employees having Lowest annual income: 
 [[ 1. 19. 15. 39.]
 [ 2. 21. 15. 81.]]


In [191]:
Cust_idmax=Shopping_data[0: ,2].max()
Cust_idmax
Custmax=np.where(Shopping_data[0: ,2]==Cust_idmax)
print("\nHighest annual income:",Cust_idmax,"\n","\nIds of employees having Highest annual income:","\n",Shopping_data[Custmax])


Highest annual income: 137.0 
 
Ids of employees having Highest annual income: 
 [[199.  32. 137.  18.]
 [200.  30. 137.  83.]]


# Task 4

In [213]:
Cust_75=np.where((Shopping_data[0: ,3]>75) & (Shopping_data[0: ,2]>=35) & (Shopping_data[0: ,1]<45) )

print("\nFollowing are the Customers eligible for discount:","\n\n",Shopping_dataa[Cust_75],"\n\nCount of Customers eligible for discount:",np.size(Cust_75))


Following are the Customers eligible for discount: 

 [[ 42.  24.  38.  92.  20.]
 [124.  39.  69.  91.  46.]
 [126.  31.  70.  77.  28.]
 [128.  40.  71.  95.  11.]
 [136.  29.  73.  88.  19.]
 [142.  32.  75.  93.  38.]
 [144.  32.  76.  87.  26.]
 [146.  28.  77.  97.  37.]
 [150.  34.  78.  90.  17.]
 [152.  39.  78.  88.  27.]
 [154.  38.  78.  76.  42.]
 [156.  27.  78.  89.  20.]
 [158.  30.  78.  78.  41.]
 [162.  29.  79.  83.  48.]
 [164.  31.  81.  93.  20.]
 [168.  33.  86.  95.  24.]
 [174.  36.  87.  92.  23.]
 [176.  30.  88.  86.  15.]
 [180.  35.  93.  90.  11.]
 [182.  32.  97.  86.  34.]
 [184.  29.  98.  88.  30.]
 [186.  30.  99.  97.  27.]
 [190.  36. 103.  85.  38.]
 [194.  38. 113.  91.  11.]
 [196.  35. 120.  79.  14.]
 [200.  30. 137.  83.  43.]] 

Count of Customers eligible for discount: 26


# Task 5

In [171]:
disc=np.random.randint(10,50,200)
print(disc)
discc=disc.reshape(200,1)
discc.shape

[31 14 14 38 29 48 33 18 46 19 16 13 46 29 47 46 32 34 29 14 30 37 34 34
 32 24 49 13 38 10 16 36 13 41 16 10 10 37 22 46 29 20 22 20 36 43 46 48
 31 16 22 12 35 32 16 47 38 34 35 37 47 25 11 39 40 45 44 17 31 39 48 16
 26 35 25 20 24 29 34 23 13 42 16 37 30 16 49 24 15 27 22 28 18 32 17 36
 20 15 32 16 23 21 36 23 35 46 28 39 31 39 27 25 35 49 20 13 35 10 32 34
 34 48 11 46 23 28 42 11 46 43 48 12 16 40 13 19 14 45 28 25 32 38 21 26
 45 37 27 47 37 17 41 27 37 42 47 20 46 41 35 18 24 48 37 20 45 12 11 24
 12 40 29 23 39 23 41 15 13 20 36 11 26 34 21 30 48 27 40 25 31 38 13 27
 35 11 46 14 36 20 11 43]


(200, 1)

In [195]:
Shopping_dataa=np.append(Shopping_data,discc,axis=1)
print("Shopping Data icluding Christmas Discount:","\n",Shopping_dataa)


Shopping Data icluding Christmas Discount: 
 [[  1.  19.  15.  39.  31.]
 [  2.  21.  15.  81.  14.]
 [  3.  20.  16.   6.  14.]
 [  4.  23.  16.  77.  38.]
 [  5.  31.  17.  40.  29.]
 [  6.  22.  17.  76.  48.]
 [  7.  35.  18.   6.  33.]
 [  8.  23.  18.  94.  18.]
 [  9.  64.  19.   3.  46.]
 [ 10.  30.  19.  72.  19.]
 [ 11.  67.  19.  14.  16.]
 [ 12.  35.  19.  99.  13.]
 [ 13.  58.  20.  15.  46.]
 [ 14.  24.  20.  77.  29.]
 [ 15.  37.  20.  13.  47.]
 [ 16.  22.  20.  79.  46.]
 [ 17.  35.  21.  35.  32.]
 [ 18.  20.  21.  66.  34.]
 [ 19.  52.  23.  29.  29.]
 [ 20.  35.  23.  98.  14.]
 [ 21.  35.  24.  35.  30.]
 [ 22.  25.  24.  73.  37.]
 [ 23.  46.  25.   5.  34.]
 [ 24.  31.  25.  73.  34.]
 [ 25.  54.  28.  14.  32.]
 [ 26.  29.  28.  82.  24.]
 [ 27.  45.  28.  32.  49.]
 [ 28.  35.  28.  61.  13.]
 [ 29.  40.  29.  31.  38.]
 [ 30.  23.  29.  87.  10.]
 [ 31.  60.  30.   4.  16.]
 [ 32.  21.  30.  73.  36.]
 [ 33.  53.  33.   4.  13.]
 [ 34.  18.  33.  92.  41.]
 [ 

# Task 6

In [204]:
Cust_45=np.where(Shopping_dataa[0: ,4]>45)

print("Customers getting discount more than 45%:","\n\n",Shopping_dataa[Cust_45])

Customers getting discount more than 45%: 

 [[  6.  22.  17.  76.  48.]
 [  9.  64.  19.   3.  46.]
 [ 13.  58.  20.  15.  46.]
 [ 15.  37.  20.  13.  47.]
 [ 16.  22.  20.  79.  46.]
 [ 27.  45.  28.  32.  49.]
 [ 40.  20.  37.  75.  46.]
 [ 47.  50.  40.  55.  46.]
 [ 48.  27.  40.  47.  48.]
 [ 56.  47.  43.  41.  47.]
 [ 61.  70.  46.  56.  47.]
 [ 71.  70.  49.  55.  48.]
 [ 87.  55.  57.  58.  49.]
 [106.  21.  62.  42.  46.]
 [114.  19.  64.  46.  49.]
 [122.  38.  67.  40.  48.]
 [124.  39.  69.  91.  46.]
 [129.  59.  71.  11.  46.]
 [131.  47.  71.   9.  48.]
 [148.  32.  77.  74.  47.]
 [155.  47.  78.  16.  47.]
 [157.  37.  78.   1.  46.]
 [162.  29.  79.  83.  48.]
 [185.  41.  99.  39.  48.]
 [195.  47. 120.  16.  46.]]
